#!/bin/sh

. ./scripts/common/print.sh
./scripts/common/upstream.sh

pkg="$1"

if [ -z "$pkg" ]; then
	print_header $error "Please inform a package to be copied from upstream"
	exit 1
fi

cp --recursive --force --no-target-directory /tmp/void-packages/srcpkgs/"$pkg" srcpkgs/"$pkg"
