#!/bin/sh

. ./scripts/common/print.sh

./scripts/common/upstream.sh

arch="$1"

if [ -z "$arch" ]; then
	print_header $error "No architecture is set"
	exit 1
fi

shift

packages="$*"

# If no specific package has been specified, let's build them all.
if [ -z "$packages" ]; then
	packages="$(git ls-files 'srcpkgs/*' | cut --delimiter / --fields 2 | uniq)"
fi

print_header $info "Preparing output directories"
if ! ./scripts/local/prepare.sh > out/msg 2>&1; then
	print_header $error "Could not prepare output directories"
	print_msg "$(cat out/msg)"
	exit 1
fi

archs="$arch $arch-musl"

print_header $info "Purging 'out/dist'"
if ! rm --force --recursive out/dist > out/msg 2>&1; then
	print_header $error "Could not purge 'out/dist'"
	print_msg "$(cat out/msg)"
	exit 1
fi


for arch in $archs; do
	print_header $info "Building requested packages for '$arch'"

	case "$arch" in
		*-musl) bootstrap_arch=x86_64-musl ;;
		*)      bootstrap_arch=x86_64 ;;
	esac
	case "$bootstrap_arch" in
		*-musl) libc="musl" ;;
		*)      libc="glibc" ;;
	esac

	print_msg "Bootstrap architecture for this build: '$bootstrap_arch'"
	print_msg "Creating 'out/dist/$libc'"
	mkdir --parent out/dist/"$libc"

	print_header $info "Removing 'void-packages' repository"
	if ! rm --recursive --force void-packages > out/msg 2>&1; then
		print_header $error "Could not remove previous existing 'void-packages' repository"
		print_msg "$(cat out/msg)"
		exit 1
	fi

	print_header $info "Cloning fresh version of 'void-packages'"
	if ! git clone --depth 1 https://github.com/void-linux/void-packages.git > out/msg 2>&1; then
		print_header $error "Could not clone 'void-packages'"
		print_msg "$(cat out/msg)"
	fi

	print_header $info "Patching 'common/shlibs'"
	if ! cat shlibs > out/msg 2>&1; then
		print_header $error "Could not patch 'common/shlibs'"
		print_msg "$(cat out/msg)"
		exit 1
	else
		cat out/msg >> void-packages/common/shlibs
	fi

	for pkg in $packages; do
		if [ -L srcpkgs/"$pkg" ]; then
			continue
		fi

		print_header $info "Building '$pkg' for '$arch'"

		if [ ! -e data/"$pkg".ignore ]; then
			case "$pkg" in
				*-devel) ;;
				*)
					print_msg "Updating checksum of '$pkg' for '$arch'"
					if ! ./scripts/local/checksum.sh "$bootstrap_arch" "$arch" "$pkg" > out/msg 2>&1; then
						print_header $warn "Could not update checksum of '$pkg' for '$arch'"
						print_msg "$(cat out/msg)"
						continue
					fi
					;;
			esac
		fi

		print_msg "Copying all custom sources to 'void-packages'"
		for custom_pkg in srcpkgs/*; do
			print_msg "Copying '$custom_pkg'"

			if ! rm --force --recursive void-packages/"$custom_pkg" > out/msg 2>&1; then
				print_header $error "Could not clean '$custom_pkg' in 'void-packages'"
				print_msg "$(cat out/msg)"
				exit 1
			fi

			if ! cp --recursive --force "$custom_pkg" void-packages/"$custom_pkg" > out/msg 2>&1; then
				print_header $error "Could not copy '$custom_pkg' to 'void-packages'"
				print_msg "$(cat out/msg)"
				exit 1
			fi
		
			if [ -e "$custom_pkg"-devel ]; then
				print_msg "Copying '$custom_pkg-devel' into 'void-packages'"
				if ! rm --force --recursive void-packages/"$custom_pkg"-devel > out/msg 2>&1; then
					print_header $error "Could not clean '$custom_pkg-devel' in 'void-packages'"
					print_msg "$(cat out/msg)"
					exit 1
				fi

				if ! cp --recursive --force "$custom_pkg"-devel void-packages/"$custom_pkg"-devel > out/msg 2>&1; then
					print_header $error "Could not copy '$custom_pkg-devel' to 'void-packages'"
					print_msg "$(cat out/msg)"
					exit 1
				fi
			fi
		done

		print_msg "Started packaging '$pkg' for '$arch'"
		./scripts/local/build.sh "$bootstrap_arch" "$arch" "$pkg" > out/msg 2>&1
		exit_code=$?
		if [ $exit_code -eq 0 ]; then
			print_msg "Finished building '$pkg' for '$arch'"
		elif [ $exit_code -eq 2 ]; then
			print_header $warn "Could not build '$pkg' for '$arch'"
			print_msg "Check logs at 'out/log/$pkg-$arch.log'"
		else
			print_header $error "Failed to build package '$pkg' for '$arch'"
			print_msg "$(cat out/msg)"
			exit 1
		fi
	done

	print_header $info "Copying binaries to '$arch' repository"
	if ! cp --recursive --force out/dist/"$libc"/. void-bins/"$libc"/ > out/msg 2>&1; then
		print_header $error "Could not copy binaries from 'out/dist/$libc' to 'void-bins'"
		print_msg "$(cat out/msg)"
		exit 1
	fi

	print_header $info "Signing packages for '$arch'"
	if ! ./scripts/local/sign.sh "$bootstrap_arch" "$arch" > out/msg 2>&1; then
		print_header $warn "Could not sign packages for '$arch'"
		print_msg "$(cat out/msg)"
	fi
done

print_header $info "Cleaning up output directory"
rm --force out/msg
rm --recursive --force void-packages
