#!/bin/sh

pkgname="$1"

# Update package or create it.
if [ -d srcpkgs/"$pkgname" ]; then
	cp --force --recursive --no-target-directory void-lab/srcpkgs/"$pkgname" srcpkgs/"$pkgname" || exit 1
	version="$(./void-lab/xbps-src show "$pkgname" | sed -n '/^version/s/[^:]*:[\t]*//p')"
	revision="$(./void-lab/xbps-src show "$pkgname" | sed -n '/^revision/s/[^:]*:[\t]*//p')"
	git add srcpkgs/"$pkgname" && git commit --message "$pkgname: Update to version $version-$revision"
else
	cp --recursive void-lab/srcpkgs/"$pkgname" srcpkgs/"$pkgname" || exit 1
	git add srcpkgs/"$pkgname" && git commit --message "Add new package \"$pkgname\""
fi

if [ "$?" -eq 0 ]; then
	echo "Cleaning upstream directory..."
	cd void-lab
	pkgpath="srcpkgs/$pkgname"
	git restore "$pkgpath" > /dev/null 2>&1 || rm --recursive --force "$pkgpath"
fi
