#!/bin/sh

. ./scripts/common/print.sh

for libc in void-bins/*; do
	if [ ! -d "$libc" ]; then
		continue
	fi

	export XBPS_TARGET_ARCH="$arch"

	print_header $info "Signing repository for '$libc'"

	if ! xbps-rindex --add "$libc"/*.xbps > out/msg 2>&1; then
		print_header $error "Could not register binaries for '$libc'"
		print_msg "$(cat out/msg)"
		exit 1
	fi

	if ! xbps-rindex --sign --privkey data/private.pem --signedby "Gabriel Sanches" "$libc" > out/msg 2>&1; then
		print_header $error "Could not sign repository for '$libc'"
		print_msg "$(cat out/msg)"
		exit 1
	fi

	if ! xbps-rindex --sign-pkg --privkey data/private.pem "$libc"/*.xbps > out/msg 2>&1; then
		print_header $error "Could not sign binaries for '$libc'"
		print_msg "$(cat out/msg)"
		exit 1
	fi
done
