#!/bin/sh

title="$1"
workdir="${2:-"$(pwd)"}"

echo "Using \"$workdir\" as commit directory"
cd "$workdir"

branch="$(basename "$workdir")"

git fetch
git remote set-url origin "https://$CI_REPO_OWNER:$ACCESS_TOKEN@codeberg.org/$CI_REPO.git"
git config --global user.name "$CI_COMMIT_AUTHOR"
git config --global user.email "$CI_COMMIT_AUTHOR_EMAIL"

echo "Changes:"
git status --short --ignore-submodules=dirty
git add --all && git commit --file - <<EOF
$title

Commit generated by Woodpecker CI:
  * Build #$CI_BUILD_NUMBER
  * Parent build #$CI_BUILD_PARENT
  * CI job #$CI_JOB_NUMBER
EOF

git push --quiet --set-upstream origin "$branch"
