#!/bin/sh

title="$1"
branch="${2:-"pages"}"

git switch "$branch" || git switch --create "$branch"
git config --global user.name "$CI_COMMIT_AUTHOR"
git config --global user.email "$CI_COMMIT_AUTHOR_EMAIL"
git commit --all --file - <<EOF
$title

Commit generated by Woodpecker CI:
  * Build #$CI_BUILD_NUMBER
  * Parent build #$CI_BUILD_PARENT
  * CI job #$CI_JOB_NUMBER
EOF
git push --set-upstream "$branch"
