stages:
  - publish

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  ADDED_PATH: /tmp/added
  MODIFIED_PATH: /tmp/modified
  DELETED_PATH: /tmp/deleted
  PKGS_PATH: /tmp/pkgs

include: common/*.yml
