stages:
  - prepare
  - publish
  - update

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  ADDED_PATH: /tmp/added
  MODIFIED_PATH: /tmp/modified
  DELETED_PATH: /tmp/deleted
  REBUILD_PATH: /tmp/rebuild
  PKGS_PATH: /tmp/pkgs
  UPSTREAM_PATH: /tmp/upstream
  LAST_DEPLOYMENT_COMMIT_FILE: last_deployment_commit
  LAST_DEPLOYMENT_COMMIT_PATH: /tmp/last_deployment_commit
  PAGES_BRANCH: pages
  ARTIFACTS_PATH: artifacts

prepare_pkgs:
  stage: prepare
  rules:
    - changes:
        - .gitlab-ci.yml
        - common/*.yml
        - common/prepare.sh
        - common/build.sh
      variables:
        IS_CI_UPDATE: "true"
    - changes:
        - srcpkgs/**/*
    - changes:
        - common/deploy.sh
      variables:
        DEPLOYMENT_ONLY: "true"
  image: ghcr.io/void-linux/void-linux:20210220rc01-thin-x86_64
  script:
    - xbps-install --sync --update --yes
    - xbps-install --yes git
    - ./common/prepare.sh
    - cp --recursive --force --no-target-directory /tmp "$ARTIFACTS_PATH"
  artifacts:
    paths:
      - $ARTIFACTS_PATH

.publish_template:
  stage: publish
  rules:
    - changes:
        - .gitlab-ci.yml
        - common/$ARCH.yml
        - common/prepare.sh
        - common/build.sh
      variables:
        IS_CI_UPDATE: "true"
    - changes:
        - srcpkgs/**/*
    - changes:
        - common/deploy.sh
      variables:
        DEPLOYMENT_ONLY: "true"
  resource_group: publishing
  image: ghcr.io/void-linux/xbps-src-masterdir:20210313rc01-$VOID_BOOTSTRAP
  script:
    - xbps-install --sync --update --yes
    - xbps-install --yes git
    - rm -rf /tmp && mv --force "$ARTIFACTS_PATH" /tmp
    - ./common/build.sh
    - ./common/deploy.sh
    - cp --recursive --force --no-target-directory /tmp "$ARTIFACTS_PATH"
  artifacts:
    paths:
      - $ARTIFACTS_PATH

include: common/*.yml

update_deployment_pivot:
  stage: update
  rules:
    - exists: 
      - $ARTIFACTS_PATH/$LAST_DEPLOYMENT_COMMIT_PATH
  image: ghcr.io/void-linux/void-linux:20210220rc01-thin-x86_64
  script:
    - xbps-install --sync --update --yes
    - xbps-install --yes git
    - rm -rf /tmp && mv --force "$ARTIFACTS_PATH" /tmp
    - 'cat "$LAST_DEPLOYMENT_COMMIT_PATH" > "$LAST_DEPLOYMENT_COMMIT_FILE"'
    - 'git config --global user.name "GitLab CI (job #$CI_JOB_ID)"'
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git add "$LAST_DEPLOYMENT_COMMIT_FILE"
    - git commit --message "Update deployment checkpoint"
    - git push --force --quiet origin "$PAGES_BRANCH" || exit 1
