stages:
  - publish

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  ADDED_PATH: /tmp/added
  MODIFIED_PATH: /tmp/modified
  DELETED_PATH: /tmp/deleted
  REBUILD_PATH: /tmp/rebuild
  PKGS_PATH: /tmp/pkgs
  UPSTREAM_PATH: /tmp/upstream
  LAST_DEPLOYMENT_COMMIT_FILE: last_deployment_commit
  LAST_DEPLOYMENT_COMMIT_PATH: /tmp/last_deployment_commit
  PAGES_BRANCH: pages

.publish_template:
  stage: publish
  rules:
    - changes:
        - .gitlab-ci.yml
        - common/$ARCH.yml
        - common/prepare.sh
        - common/build.sh
      variables:
        IS_CI_UPDATE: "true"
    - changes:
        - srcpkgs/**/*
    - changes:
        - common/deploy.sh
      variables:
        DEPLOYMENT_ONLY: "true"
  resource_group: publishing
  image: ghcr.io/void-linux/xbps-src-masterdir:20210313rc01-$VOID_BOOTSTRAP
  script:
    - xbps-install --sync --update --yes
    - xbps-install --yes git
    - git fetch
    - ./common/prepare.sh
    - ./common/build.sh
    - ./common/deploy.sh

include: common/*.yml
