#!/bin/sh

cd "/usr/libexec/@PKGNAME@"

exec java \
	-Declipse.application=org.eclipse.jdt.ls.core.id1 \
	-Dosgi.bundles.defaultStartLevel=4 \
	-Declipse.product=org.eclipse.jdt.ls.core.product \
	-Dosgi.checkConfiguration=true \
	-Dosgi.sharedConfiguration.area=/usr/share/@PKGNAME@/config_linux \
	-Dosgi.sharedConfiguration.area.readOnly=true \
	-Dosgi.configuration.cascaded=true \
	-Dlog.protocol=true \
	-Dlog.level=ALL \
	-Xms1G \
	--add-modules=ALL-SYSTEM \
	--add-opens java.base/java.util=ALL-UNNAMED \
	--add-opens java.base/java.lang=ALL-UNNAMED \
	-jar ./plugins/org.eclipse.equinox.launcher_*.jar \
	"$@"
