#!/bin/sh

tmpdir=$(mktemp -d "/tmp/@PKGNAME@.XXXXX")
default_logpath="$tmpdir/log"
default_metapath="$tmpdir/meta"

trap "{ rm -rf $tmpdir; }" EXIT

exec /usr/libexec/@PKGNAME@/bin/@PKGNAME@ \
	--logpath="$default_logpath" \
	--metapath="$default_metapath" \
	"$@"
