pipeline:
  publish:
    image: "gbrlsnchs/void-linux-ci"
    commands:
      - "./scripts/generate_pages.sh"
      - "./scripts/commit.sh /tmp/changelog_file pages"
      - "./scripts/clean_up.sh"
    secrets: ["access_token"]

depends_on: ["package"]
