pipeline:
  publish:
    image: "gbrlsnchs/void-linux-ci"
    commands:
      - "./scripts/generate_pages.sh"
      - "CI_PUBLISH_BINS=1 ./scripts/commit.sh /tmp/changelog pages"
      - "./scripts/clean_up.sh"
    secrets: ["access_token", "binrepo_token"]

depends_on: ["package"]
