matrix:
  include:
    - ARCH: "x86_64"
      BOOTSTRAP_ARCH: "x86_64"
    - ARCH: "x86_64-musl"
      BOOTSTRAP_ARCH: "x86_64-musl"

pipeline:
  build:
    image: "ghcr.io/void-linux/xbps-src-masterdir:20210313rc01-${BOOTSTRAP_ARCH}"
    commands:
      - "xbps-install --sync --update --yes"
      - "xbps-install --yes git openssh"
      - "./scripts/build.sh"
      - "./scripts/sign.sh"
      - './scripts/commit.sh "$ARCH: Publish updates"'
    secrets: ["access_token", "signing_key"]

depends_on: ["prepare"]
