matrix:
  include:
    - ARCH: "x86_64"
      BOOTSTRAP_ARCH: "x86_64"
      LIBC: "glibc"
    - ARCH: "x86_64-musl"
      BOOTSTRAP_ARCH: "x86_64-musl"
      LIBC: "musl"

pipeline:
  xbps-src:
    image: "ghcr.io/void-linux/xbps-src-masterdir:20210313rc01-${BOOTSTRAP_ARCH}"
    commands:
      - "xbps-install --sync --update --yes"
      - "xbps-install --yes git openssh"
      - "./scripts/build.sh"
      - './scripts/commit.sh "Prepare compiled binaries" "$LIBC"'
    secrets: ["access_token"]

depends_on: ["prepare"]
