pipeline:
  list:
    image: "gbrlsnchs/void-linux-ci"
    pull: true
    commands:
      - "./scripts/list.sh"
  list-rebuild:
    when:
      path: [".woodpecker/*", "scripts/*", "container/*"]
    image: "gbrlsnchs/void-linux-ci"
    commands:
      - "./scripts/list_rebuild.sh"
  commit:
    image: "gbrlsnchs/void-linux-ci"
    commands:
      - "./scripts/commit.sh 'Prepare packages to build' ci"
    secrets: ["access_token"]

branches: ["trunk"]
