pipeline:
  list:
    image: "debian:sid"
    commands:
      - "apt-get update"
      - "apt-get install --yes git"
      - "./scripts/list.sh"
  list-rebuild:
    when:
      path: [".woodpecker/*", "scripts/*"]
    image: "debian:sid"
    commands:
      - "./scripts/list_rebuild.sh"
  commit:
    image: "debian:sid"
    commands:
      - "apt-get update"
      - "apt-get install --yes git"
      - "./scripts/commit.sh 'Prepare packages to build' ci"
    secrets: ["access_token"]

branches: ["trunk"]
