pipeline:
  list:
    image: "debian:sid"
    commands:
      - "apt-get update"
      - "apt-get install --yes git"
      - "./common/woodpecker/list.sh"
  list_rebuild:
    when:
      path: [".woodpecker/*", "common/woodpecker/**/*"]
    image: "debian:sid"
    commands:
      - "./common/woodpecker/list_rebuild.sh"
  commit:
    image: "debian:sid"
    commands:
      - "apt-get update"
      - "apt-get install --yes git"
      - "./common/woodpecker/set_remote.sh"
      - "./common/woodpecker/commit.sh 'Prepare packages to build' ci"
    secrets: ["access_token"]

branches: ["trunk"]
