matrix:
  include:
    - ARCH: "x86_64"
      BOOTSTRAP_ARCH: "x86_64"
      LIBC: "glibc"
    - ARCH: "x86_64-musl"
      BOOTSTRAP_ARCH: "x86_64-musl"
      LIBC: "musl"

pipeline:
  package:
    image: "ghcr.io/void-linux/xbps-src-masterdir:20210313rc01-${BOOTSTRAP_ARCH}"
    commands:
      - "xbps-install --sync --update --yes"
      - "xbps-install --yes git openssh"
      - "./common/woodpecker/build.sh"
      - "./common/woodpecker/commit.sh 'Prepare compiled binaries to get published' pre"
    secrets: ["access_token"]

depends_on: ["prepare"]
